version: '3.1'
services:
      dev-db:
        container_name: dev-db
        image: postgres:12-alpine
        restart: always
        ports:
          - "5441:5432"
        environment:
          POSTGRES_DB: sistema-bancario-db
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        volumes:
          - ./data:/var/lib/postgresql/data